name: Deploy

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

 

    steps:
    - uses: actions/checkout@v4
   
    - run: docker build . -t naga1332/jenkinangularjs
    - run: echo "${{secrets.DOCKERHUB_PASSWORD}}" | docker login -u naga1332 --password-stdin
    - run: docker push naga1332/jenkinangularjs:latest
 
